[project]
name = "slidev-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crawl4ai>=0.7.0",
    "jinja2>=3.1.6",
    "mcp[cli]>=1.9.4",
    "usermcp>=0.1.2",
]
